### PR TITLE
Enhanced device ID checking to allow usage of certain available clones

### PR DESCRIPTION
**Pull request by holzachr**
Proposing changes according to
https://github.com/ElectronicCats/mpu6050/issues/21

### CODE REVIEW

**Review by sabas1080 — APPROVED** [review]

**Comment by sabas1080** [comment]
Nice, ok for me, thanks @holzachr

**Comment by sergioguimaraes** [comment]
Dear all, after made the proposed changes, the error remais the same. Tested the IC, it is working and returning whoami as 0x98.

**Comment by sabas1080** [comment]
@sergioguimaraes any possible solution?

**Comment by sylvaneau** [comment]
Hi,

I think there is a mistake in the suggested value, should be `0xC`, not `0x4C`.

This is because the MPU6050 library reads only the 6 significant bits in the register (from bit 6 to bit 1), the two other bits are reserved.

The full register value is 0x98 (10011000), so the library watches for the bits 6-1 : 001100 which gives 0xC.

I can subit a PR if you want to.

I would like to mention that here is also some code such as `int16_t MPU6050::getZAccelOffset()` which relies on the device id on this line :
`uint8_t SaveAddress = ((getDeviceID() < 0x38 )? MPU6050_RA_YA_OFFS_H:0x7A);`

we are lucky though as this should not break the code, however i'm really not confident in the quality of these clones and of their register locations...

**Pull request merged**
